import { GoogleOauth2ContextProvider } from '@/context/GoogleOauth2Context';
import { NotifiContextWrapper } from '@/context/NotifiContextWrapper';
import type { Metadata } from 'next';

import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <GoogleOauth2ContextProvider>
          <NotifiContextWrapper>{children}</NotifiContextWrapper>
        </GoogleOauth2ContextProvider>
      </body>
    </html>
  );
}
