export type WalletBlockchain =
  | 'SOLANA'
  | 'ETHEREUM'
  | 'OFF_CHAIN'
  | 'AVALANCHE'
  | 'APTOS'
  | 'ACALA'
  | 'POLYGON'
  | 'ARBITRUM'
  | 'BINANCE'
  | 'NEAR'
  | 'OPTIMISM'
  | 'INJECTIVE'
  | 'SUI'
  | 'OSMOSIS'
  | 'EVMOS';