import { gql } from 'graphql-request';

export const stateChangedSubscriptionQuery = `
  subscription stateChanged {
    stateChanged {
      ... on TargetStateChangedEvent {
        __typename
        targetId
        targetType
        timestamp
      }
      ... on NotificationHistoryStateChangedEvent {
        __typename
        timestamp
      }
    }
  }
` as const;

//NOTE: ⬇ For autogenerated types only. no runtime usage. (gql subscription runtime logic is handled by NotifiSubscriptionService instance)
const _unusedQuery = gql`
  ${stateChangedSubscriptionQuery}
`;
