import { gql } from 'graphql-request';

export const stateChangedSubscriptionQuery = `
  subscription stateChanged {
    stateChanged {
      __typename
    }
  }
` as const;

//NOTE: ⬇ For autogenerated types only. no runtime usage. (gql subscription runtime logic is handled by NotifiSubscriptionService instance)
gql`
  ${stateChangedSubscriptionQuery}
`;
