import { TenantUserAlertFragment } from '../fragments/TenantUserAlertFragment.gql';
import { TenantUserFragment } from '../fragments/TenantUserFragment.gql';
import { gql } from 'graphql-request';

export const tenantEntityChangedSubscriptionQuery = `
  subscription tenantEntityChanged {
    tenantEntityChanged {
      __typename
      ... on UserCreatedEvent {
        user {
          ...TenantUserFragment
        }
      }
      ... on AlertCreatedEvent {
        alert {
          ...TenantUserAlertFragment
        }
        user {
          ...TenantUserFragment
        }
      }
      ... on AlertDeletedEvent {
        alertId
        user {
          ...TenantUserFragment
        }
      }
    }
  }
  ${TenantUserAlertFragment}
  ${TenantUserFragment}
` as const;

//NOTE: ⬇ For autogenerated types only. no runtime usage. (gql subscription runtime logic is handled by NotifiSubscriptionService instance)
gql`
  ${tenantEntityChangedSubscriptionQuery}
`;
