import { ActiveAlertFragment } from '../fragments/ActiveAlertFragment.gql';
import { gql } from 'graphql-request';

export const tenantActiveAlertChangedSubscriptionQuery = `
  subscription tenantActiveAlertChanged {
    tenantActiveAlertChanged {
      __typename
      ... on ActiveAlertCreatedEvent {
        __typename
        activeAlert {
          ...ActiveAlertFragment
        }
      }
      ... on ActiveAlertDeletedEvent {
        alertId
        timestamp
        userId
      }
    }
  }
  ${ActiveAlertFragment}
` as const;

//NOTE: ⬇ For autogenerated types only. no runtime usage. (gql subscription runtime logic is handled by NotifiSubscriptionService instance)
gql`
  ${tenantActiveAlertChangedSubscriptionQuery}
`;
